#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE 30
#define RGB_MATRIX_DEFAULT_SAT 200
#define RGB_MATRIX_DEFAULT_VAL 120
#define RGB_MATRIX_DEFAULT_SPD 25